{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.playsoftware.j2meloader",
    "module": "j2me-loader",
    "version": "1.8.2-external-output.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-android"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "com.github.billthefarmer",
          "module": "mididriver",
          "version": {
            "requires": "v1.21"
          }
        },
        {
          "group": "com.github.nikita36078",
          "module": "pngj",
          "version": {
            "requires": "2.2.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.nikita36078",
          "module": "mobile-ffmpeg",
          "version": {
            "requires": "v4.3.2-compact"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "com.github.nikita36078",
          "module": "filepicker",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "j2me-loader-1.8.2-external-output.5.aar",
          "url": "j2me-loader-1.8.2-external-output.5.aar",
          "size": 2232500,
          "sha512": "7124d53b34714b9628eabe27444a1dbb1b8c0ae41062c36a0d86f2755ed2fcc9cb0839f1445969badebd10b3807e63b34ca824d4d3d886659453b206f52e2169",
          "sha256": "e0029c984e9f2c04e67db5dde008005f8ac3384848e5842b6551bf14e3a49ccb",
          "sha1": "4f4ae791120bccb4f03bc6f3cdbf5dca9af5af39",
          "md5": "a21d051d95b9cdde5c197e8ad96e481e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-android"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "com.github.billthefarmer",
          "module": "mididriver",
          "version": {
            "requires": "v1.21"
          }
        },
        {
          "group": "com.github.nikita36078",
          "module": "pngj",
          "version": {
            "requires": "2.2.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.nikita36078",
          "module": "mobile-ffmpeg",
          "version": {
            "requires": "v4.3.2-compact"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "com.github.nikita36078",
          "module": "filepicker",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "j2me-loader-1.8.2-external-output.5.aar",
          "url": "j2me-loader-1.8.2-external-output.5.aar",
          "size": 2232500,
          "sha512": "7124d53b34714b9628eabe27444a1dbb1b8c0ae41062c36a0d86f2755ed2fcc9cb0839f1445969badebd10b3807e63b34ca824d4d3d886659453b206f52e2169",
          "sha256": "e0029c984e9f2c04e67db5dde008005f8ac3384848e5842b6551bf14e3a49ccb",
          "sha1": "4f4ae791120bccb4f03bc6f3cdbf5dca9af5af39",
          "md5": "a21d051d95b9cdde5c197e8ad96e481e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "j2me-loader-1.8.2-external-output.5-sources.jar",
          "url": "j2me-loader-1.8.2-external-output.5-sources.jar",
          "size": 1463902,
          "sha512": "93e5c41d774fc3c95a1bbfb647fdba2ce3d153750ae847057d5a1dcc1a2e9869fa56157374d16d3d738b6bc21918ad6dbf280cc16b8b7d7fe8abeb7392ef379c",
          "sha256": "4495366ab6cab635ac7940edc2781e2a7fc013804de655c72440017fda3ba394",
          "sha1": "3eaa552990f78cf7dc3bb1edeffc91413dde9621",
          "md5": "1f5482ae5056378c0af5e1eaa460acaf"
        }
      ]
    }
  ]
}
