{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.playsoftware.j2meloader",
    "module": "j2me-loader",
    "version": "1.8.2-external-output.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-android"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "com.github.billthefarmer",
          "module": "mididriver",
          "version": {
            "requires": "v1.21"
          }
        },
        {
          "group": "com.github.nikita36078",
          "module": "pngj",
          "version": {
            "requires": "2.2.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.nikita36078",
          "module": "mobile-ffmpeg",
          "version": {
            "requires": "v4.3.2-compact"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "com.github.nikita36078",
          "module": "filepicker",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "j2me-loader-1.8.2-external-output.2.aar",
          "url": "j2me-loader-1.8.2-external-output.2.aar",
          "size": 2212705,
          "sha512": "fa094fe2260c9f38e3fd7a6143ae0840b685a62a092799bcaf2fce7dcec5c7a2d9eff3d4695a92b8f90a8d48753efa93ea0b75540a42a30346a1fd51d622c9eb",
          "sha256": "0b2d51b585c7b2409b744072dcff54de15d3960f87164617bd56a4c4755ca055",
          "sha1": "27121c0bd8d795942f9936e952b5b72032bb9952",
          "md5": "9bd6e7b6287677c820f707de495a56a2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-android"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "com.github.billthefarmer",
          "module": "mididriver",
          "version": {
            "requires": "v1.21"
          }
        },
        {
          "group": "com.github.nikita36078",
          "module": "pngj",
          "version": {
            "requires": "2.2.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.nikita36078",
          "module": "mobile-ffmpeg",
          "version": {
            "requires": "v4.3.2-compact"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "com.github.nikita36078",
          "module": "filepicker",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "j2me-loader-1.8.2-external-output.2.aar",
          "url": "j2me-loader-1.8.2-external-output.2.aar",
          "size": 2212705,
          "sha512": "fa094fe2260c9f38e3fd7a6143ae0840b685a62a092799bcaf2fce7dcec5c7a2d9eff3d4695a92b8f90a8d48753efa93ea0b75540a42a30346a1fd51d622c9eb",
          "sha256": "0b2d51b585c7b2409b744072dcff54de15d3960f87164617bd56a4c4755ca055",
          "sha1": "27121c0bd8d795942f9936e952b5b72032bb9952",
          "md5": "9bd6e7b6287677c820f707de495a56a2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "j2me-loader-1.8.2-external-output.2-sources.jar",
          "url": "j2me-loader-1.8.2-external-output.2-sources.jar",
          "size": 1456751,
          "sha512": "bd0a11ea99fab694df64ac439c883af9ac6e1504512f0aba4c05051b0d541589f39bada5273d6097f88e9efea91a3914c79fc8cce00efc2ccd1acd87db19330e",
          "sha256": "40a30da0dbdf06c02693973c63b844a24c5297f71106a44ddcaef59bee047098",
          "sha1": "948c5f49ba50b15fe878a4b7057d2099c0e5e87f",
          "md5": "c6cf641303f87665cb4163c9f11cb193"
        }
      ]
    }
  ]
}
