{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.playsoftware.j2meloader",
    "module": "j2me-loader",
    "version": "1.8.2-external-output.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-android"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "com.github.billthefarmer",
          "module": "mididriver",
          "version": {
            "requires": "v1.21"
          }
        },
        {
          "group": "com.github.nikita36078",
          "module": "pngj",
          "version": {
            "requires": "2.2.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.nikita36078",
          "module": "mobile-ffmpeg",
          "version": {
            "requires": "v4.3.2-compact"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "com.github.nikita36078",
          "module": "filepicker",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "j2me-loader-1.8.2-external-output.3.aar",
          "url": "j2me-loader-1.8.2-external-output.3.aar",
          "size": 2212700,
          "sha512": "a965e885280ede827c161d3c358c381d91b76b18fa304c5dd81237b3a022087f0aba5712fc737d246a72ed7d5442c50e73f1a2325b583024b91771f4dd2256cd",
          "sha256": "b209e6b5d79d9291fb01dd6ce36b62b8df437c5ac3d0c60ca2a2c085647c63a3",
          "sha1": "de9ab09bd548d3d971b7bcf09973712c854bac24",
          "md5": "9d1f29bca3a9ce8cb5aa2d14cdf92ca9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-android"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "com.github.billthefarmer",
          "module": "mididriver",
          "version": {
            "requires": "v1.21"
          }
        },
        {
          "group": "com.github.nikita36078",
          "module": "pngj",
          "version": {
            "requires": "2.2.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.nikita36078",
          "module": "mobile-ffmpeg",
          "version": {
            "requires": "v4.3.2-compact"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "com.github.nikita36078",
          "module": "filepicker",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "j2me-loader-1.8.2-external-output.3.aar",
          "url": "j2me-loader-1.8.2-external-output.3.aar",
          "size": 2212700,
          "sha512": "a965e885280ede827c161d3c358c381d91b76b18fa304c5dd81237b3a022087f0aba5712fc737d246a72ed7d5442c50e73f1a2325b583024b91771f4dd2256cd",
          "sha256": "b209e6b5d79d9291fb01dd6ce36b62b8df437c5ac3d0c60ca2a2c085647c63a3",
          "sha1": "de9ab09bd548d3d971b7bcf09973712c854bac24",
          "md5": "9d1f29bca3a9ce8cb5aa2d14cdf92ca9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "j2me-loader-1.8.2-external-output.3-sources.jar",
          "url": "j2me-loader-1.8.2-external-output.3-sources.jar",
          "size": 1456751,
          "sha512": "bd0a11ea99fab694df64ac439c883af9ac6e1504512f0aba4c05051b0d541589f39bada5273d6097f88e9efea91a3914c79fc8cce00efc2ccd1acd87db19330e",
          "sha256": "40a30da0dbdf06c02693973c63b844a24c5297f71106a44ddcaef59bee047098",
          "sha1": "948c5f49ba50b15fe878a4b7057d2099c0e5e87f",
          "md5": "c6cf641303f87665cb4163c9f11cb193"
        }
      ]
    }
  ]
}
