{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.playsoftware.j2meloader",
    "module": "j2me-loader",
    "version": "1.8.2-external-output.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-android"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "com.github.billthefarmer",
          "module": "mididriver",
          "version": {
            "requires": "v1.21"
          }
        },
        {
          "group": "com.github.nikita36078",
          "module": "pngj",
          "version": {
            "requires": "2.2.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.nikita36078",
          "module": "mobile-ffmpeg",
          "version": {
            "requires": "v4.3.2-compact"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "com.github.nikita36078",
          "module": "filepicker",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "j2me-loader-1.8.2-external-output.1.aar",
          "url": "j2me-loader-1.8.2-external-output.1.aar",
          "size": 2212448,
          "sha512": "3b29d08a67171b0abe9346d02746fede04d642105c4808c600fdd254291551382e52a4688fe318c5a5357970b7c3648b4260a9acaf4ba7fb9661dbe20fa95798",
          "sha256": "e8f837dd2b5a9980791fb1988d98f78da066b5a30303ec78f52d1d64ee072cc7",
          "sha1": "369ac4e35f9429e67c816eb13adb220d891950f4",
          "md5": "edc68c80c32dd90fe2e52338bc3e24f8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-android"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "com.github.billthefarmer",
          "module": "mididriver",
          "version": {
            "requires": "v1.21"
          }
        },
        {
          "group": "com.github.nikita36078",
          "module": "pngj",
          "version": {
            "requires": "2.2.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.nikita36078",
          "module": "mobile-ffmpeg",
          "version": {
            "requires": "v4.3.2-compact"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "com.github.nikita36078",
          "module": "filepicker",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "j2me-loader-1.8.2-external-output.1.aar",
          "url": "j2me-loader-1.8.2-external-output.1.aar",
          "size": 2212448,
          "sha512": "3b29d08a67171b0abe9346d02746fede04d642105c4808c600fdd254291551382e52a4688fe318c5a5357970b7c3648b4260a9acaf4ba7fb9661dbe20fa95798",
          "sha256": "e8f837dd2b5a9980791fb1988d98f78da066b5a30303ec78f52d1d64ee072cc7",
          "sha1": "369ac4e35f9429e67c816eb13adb220d891950f4",
          "md5": "edc68c80c32dd90fe2e52338bc3e24f8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "j2me-loader-1.8.2-external-output.1-sources.jar",
          "url": "j2me-loader-1.8.2-external-output.1-sources.jar",
          "size": 1456605,
          "sha512": "4b18f1fc3c734ab1d3ac47decfa7672d863f80a270a33bf10903f8633565f488241cebb13d07fa894dc649a0714dc29bc70a996d0fad92f3205d48a46696af13",
          "sha256": "95e6e411da5e50099a79a1399ccd8feb515f47fb4844c0ee4abf97e8e76c47a3",
          "sha1": "42b8e2e90c5f74ad2a15f7a046e34de93b04fbc8",
          "md5": "5839270d38fc3b5bf522ba813fdd1fb7"
        }
      ]
    }
  ]
}
