{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.playsoftware.j2meloader",
    "module": "j2me-loader",
    "version": "1.8.2-external-output.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-android"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "com.github.billthefarmer",
          "module": "mididriver",
          "version": {
            "requires": "v1.21"
          }
        },
        {
          "group": "com.github.nikita36078",
          "module": "pngj",
          "version": {
            "requires": "2.2.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.nikita36078",
          "module": "mobile-ffmpeg",
          "version": {
            "requires": "v4.3.2-compact"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "com.github.nikita36078",
          "module": "filepicker",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "j2me-loader-1.8.2-external-output.4.aar",
          "url": "j2me-loader-1.8.2-external-output.4.aar",
          "size": 2213126,
          "sha512": "093bd99960eb8547238ef147c227f9af6084fde0ad9e6f4b6ff0f1b117eb0c24e639f7873873621372ebfb097e04c70d387671fabc3c6c22b33634a0baec02c9",
          "sha256": "f0d5ed89dbf9e75bf9496cf69df4d326631aa5c708857a17b6bf93f7887666e0",
          "sha1": "917bfbd65bc13c6deea335e5e524a484a4788a03",
          "md5": "7d3b0284c76bfe9ca1976b9718c2949c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-android"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "com.github.billthefarmer",
          "module": "mididriver",
          "version": {
            "requires": "v1.21"
          }
        },
        {
          "group": "com.github.nikita36078",
          "module": "pngj",
          "version": {
            "requires": "2.2.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.nikita36078",
          "module": "mobile-ffmpeg",
          "version": {
            "requires": "v4.3.2-compact"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "com.github.nikita36078",
          "module": "filepicker",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "j2me-loader-1.8.2-external-output.4.aar",
          "url": "j2me-loader-1.8.2-external-output.4.aar",
          "size": 2213126,
          "sha512": "093bd99960eb8547238ef147c227f9af6084fde0ad9e6f4b6ff0f1b117eb0c24e639f7873873621372ebfb097e04c70d387671fabc3c6c22b33634a0baec02c9",
          "sha256": "f0d5ed89dbf9e75bf9496cf69df4d326631aa5c708857a17b6bf93f7887666e0",
          "sha1": "917bfbd65bc13c6deea335e5e524a484a4788a03",
          "md5": "7d3b0284c76bfe9ca1976b9718c2949c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "j2me-loader-1.8.2-external-output.4-sources.jar",
          "url": "j2me-loader-1.8.2-external-output.4-sources.jar",
          "size": 1456978,
          "sha512": "52e553f8dd4677d8231bb2ad5dd93d22cb2c6180ee0f88cd1040dbdcce5aefdd1d73572c5ba200e9bcecfc72d6ae2ba641f4c9f813ec7e331990594eb819b58f",
          "sha256": "ea236bab57bb0c36233018bde2cbccadcdb0bcbf3320ab00480ba806bb5f8e0e",
          "sha1": "70f02965c99d72e4a4bbddddd6e559b790dcde1e",
          "md5": "2004c8084ad1ee053546b2a57061595b"
        }
      ]
    }
  ]
}
